#pragma config(Sensor, S1,     touch1,         sensorTouch)
#pragma config(Sensor, S4,     touch4,         sensorTouch)
/*!!Code automatically generated by 'ROBOTC' configuration wizard !!
Configurer capteurs tactiles en sortie 1 et 4*/
/*______________________________________________________________________________________*/
int aleat;//déclarer la variable aleat
int user=0; //déclarer la variable user étant égale à 0
int repete=0;
int coups=0;
int niveau=1;
int maxi=1;
/*______________________________________________________________________________________*/

task aleatoire()// déclaration de la tache aleatoire
{// début de l'instruction
	aleat= rand()%maxi;// définir la variable aleat étant égale à un nombre aléatoire entre -l'infini et le nombre maxi (maxi) auparavent défini par l'utilisateur

	if (aleat<0){// si le nombre aléatoire généré est négatif...
		aleat=aleat-2*aleat;} // ... le mettre en positif. ex: -99 -> 99
	else if(aleat==0){// si le nombre aléatoire généré est égal à 0...
		aleat=aleat+1;//... ajouter 1 au nombre
	}
}// fin de l'instruction

/*______________________________________________________________________________________*/

void niveaux()// définir le sous-programme niveaux
{ // début de l'instruction
	while (1){ // pour toujours
		displayTextLine(1, "Niveau1:1 et 50"); // afficher sur l'écran en petits caractères et à gauche à la ligne 1: Niveau1:1 et 50
		displayTextLine(2, "Niveau2:1 et 100");
		displayTextLine(3, "Niveau3:1 et 500");
		displayTextLine(4, "Niveau4:Perso");
		displayTextLine(5, "Choisis le niveau:");
		displayCenteredBigTextLine(6, "-   %d  +", niveau); // afficher sur l'écran en gros caractères et centré à la ligne 6 - et + aux extrémités et la valeur de la variable niveau au milieu

		if(nNxtButtonPressed == kLeftButton){ // si le bouton gauche du NXT est enfoncé
			playSoundFile("! Click.rso"); // jouer un clic
			niveau=niveau-1; // diminuer d'un niveau
			displayCenteredBigTextLine(6, "-   %d  +", niveau);
			sleep(500);}// attendre 500 millisecondes
		if(nNxtButtonPressed == kRightButton){ //si le bouton gauche du NXT est enfoncé
			playSoundFile("! Click.rso");
			niveau=niveau+1;// augmenter d'un niveau
			displayCenteredBigTextLine(6, "-   %d  +", niveau);
			sleep(500);}
		if(nNxtButtonPressed == kEnterButton){//si le bouton entrée du NXT est enfoncé
			playSoundFile("! Click.rso");
			displayClearTextLine(5);// effacer la ligne 5 de l'écran
			sleep(500);
			if(niveau==1){ // si l'utilisateur a choisi le niveau 1
				maxi=50; // la borne maximale de la recherche d'un nombre aléatoire est 50
				break;}
			if(niveau==2){// si l'utilisateur a choisi le niveau 2
				maxi=100;// la borne maximale de la recherche d'un nombre aléatoire est 100
				break;}
			if(niveau==3){// si l'utilisateur a choisi le niveau 3
				maxi=500;// la borne maximale de la recherche d'un nombre aléatoire est 500
				break;}
			if(niveau==4){// si l'utilisateur a choisi le niveau 4
				eraseDisplay(); // effacer tout l'écran
				displayCenteredTextLine(1, " Nombre maximum");// afficher en petits caractères et centré à la ligne 1 Nombre maximum
				displayCenteredBigTextLine(3, "%d", maxi);// afficher la valeur de la variable maxi
				while(nNxtButtonPressed != kEnterButton){ // tant que le bouton entrée du NXT n'est pas enfoncé...
					if(nNxtButtonPressed == kLeftButton){
						playSoundFile("! Click.rso");
						maxi=maxi-1;
						displayCenteredBigTextLine(3, "%d", maxi);
						sleep(300);}

					if(SensorValue(touch1) == 1){//... si le capteur tactile pour diminuer est enfoncé
						while(SensorValue(touch1) == 1){// tant que le capteur tactile pour diminuer est enfoncé...
							maxi=maxi-1;//... diminuer la valeur de maxi de 1
							displayCenteredBigTextLine(3, "%d", maxi);
							sleep(2);}
						playSoundFile("! Click.rso");}

					if(nNxtButtonPressed == kRightButton){//... si le capteur tactile pour augmenter est enfoncé
						playSoundFile("! Click.rso");
						maxi=maxi+1;
						displayCenteredBigTextLine(3, "%d", maxi);
						sleep(300);}

					if(SensorValue(touch4) == 1){//... si le capteur tactile pour augmenter est enfoncé
						while(SensorValue(touch4) == 1){// tant que le capteur tactile pour augmenter est enfoncé...

							maxi=maxi+1;//... augmenter la valeur de maxi de 1
							displayCenteredBigTextLine(3, "%d", maxi);
							sleep(2);}
						playSoundFile("! Click.rso");}// jouer le clic juste à la fin pour ne l'avoir qu'une fois qu'on relache
				}
			}
			if(nNxtButtonPressed == kEnterButton){
				playSoundFile("! Click.rso");
				eraseDisplay();
				displayCenteredBigTextLine(3, "Ok");
				sleep(2000);
				break;// sortir du sous-programme
			}
		}
	}
}
/*______________________________________________________________________________________*/
task negatif()
{// tâche pour gérer tous les nombres à l'extérieur des bornes
	while(1)
	{
		if (maxi<=0){
			user=1;
			displayCenteredBigTextLine(3, "%d",user );
		}
		if (niveau<1){
			niveau=4;
			displayCenteredBigTextLine(6, "-   %d  +", niveau);}
		if (niveau>4){
			niveau=1;
			displayCenteredBigTextLine(6, "-   %d  +", niveau);}
		if (user<=0){
			user=maxi;
			displayCenteredBigTextLine(3, "%d",user );
		}
		if (user>maxi){
			user=1;
			displayCenteredBigTextLine(3, "%d",user );
		}
		if (maxi<1){
			maxi=1;
			displayCenteredBigTextLine(3, "%d",maxi );
		}
	}
}


/*______________________________________________________________________________________*/




task main()
// programme principal
{ while(repete==0){// tant que l'utilisateur joue et rejoue
		nVolume=10; // mettre le son au maximum
		startTask(negatif);// démarrer la tache negatif
		niveaux(); // démarrer le sous-programme niveaux
		startTask (aleatoire);// démarrer la tache negatif
		playSoundFile("! Startup.rso"); // jouer le son NXT ! Startup
		user=1;
		sleep(1000);
		displayCenteredTextLine(1, "Entre 1 et %d", maxi); // entre 1 et borne maxi définie avant
		displayCenteredBigTextLine(6, "-     +");
		displayCenteredTextLine(2, "Votre nombre :");
		displayCenteredBigTextLine(3, "%d", user);


		while(1) // pour toujours
		{


			if(nNxtButtonPressed == kLeftButton){
				playSoundFile("! Click.rso");
				user=user-1;
				displayCenteredBigTextLine(3, "%d", user);
				sleep(300);}

			if(SensorValue(touch1) == 1){
				while(SensorValue(touch1) == 1){

					user=user-1;
					displayCenteredBigTextLine(3, "%d", user);
					sleep(2);} // attendre 2 millisecondes pour aller plus vite
				playSoundFile("! Click.rso");}

			if(nNxtButtonPressed == kRightButton){
				playSoundFile("! Click.rso");
				user=user+1;
				displayCenteredBigTextLine(3, "%d", user);
				sleep(300);}

			if(SensorValue(touch4) == 1){
				while(SensorValue(touch4) == 1){

					user=user+1;
					displayCenteredBigTextLine(3, "%d", user);
					sleep(2);}
				playSoundFile("! Click.rso");}

			if(nNxtButtonPressed == kEnterButton){ // si l'utilisateur valide
				while(nNxtButtonPressed == kEnterButton){}// tant qu'il appuie ne rien faire
				coups=coups+1; // augmenter le nombre de coups
				playSoundFile("! Click.rso");
				displayClearTextLine(5);
				sleep(500);
				if(user<aleat){ // si le nombre de l'utilisateur est plus grand que le nombre généré...
					displayClearTextLine(5);
					displayCenteredTextLine(5, "C'est plus"); //... écrire c'est plus


					}else if(user>aleat){
					displayClearTextLine(5);
					displayCenteredTextLine(5, "C'est moins");

				}else if(user==aleat)// si le nombre de l'utilisateur est le nombre généré...
				{
					playSoundFile("! Applause.rso"); // applaudissment
					displayClearTextLine(5);
					displayCenteredTextLine(5, "C'est bon"); /// écrire c'est bon
					sleep(2000);
					eraseDisplay(); // effacer l'écran
					displayCenteredBigTextLine(3,"Rejouer?");
					displayCenteredTextLine(1, "En %d coups", coups);
					displayCenteredBigTextLine(6, "Non  Oui");
					while(nNxtButtonPressed == kNoButton){}// tant que l'utilisateur n'appuie pas, ne rien faire
					if(nNxtButtonPressed == kLeftButton){ // s'il ne veut pas rejouer
						repete=1; // arreter while grâce à repete
						break;} // sortir de la boucle et donc grace à repete du programme
					if(nNxtButtonPressed == kRightButton){ // s'il veut rejouer
						coups=0; // réinitialiser le nombre de coups ...
						maxi=1; // ... et le nombre maximum
						break;} // sorir de la boucle et redémmarer le programme
				}
			}

		}
	}
}
