#pragma config(Sensor, S1,     touch1,         sensorEV3_Touch)
#pragma config(Sensor, S4,     touch4,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Configurer capteurs tactiles en sortie 1 et 4*/
/*______________________________________________________________________________________*/
int aleat;//déclarer la variable aleat
int user=0; //déclarer la variable user étant égale à 0
int repete=0;
int coups=0;
int niveau=1;
int maxi=1;
int x=0;
int y=0;
int z=0;
int a=0;
/*______________________________________________________________________________________*/

task aleatoire()// déclaration de la tache aleatoire
{// début de l'instruction
	aleat= rand()%maxi;// définir la variable aleat étant égale à un nombre aléatoire entre -l'infini et le nombre maxi (maxi) auparavent défini par l'utilisateur

	if (aleat<0){// si le nombre aléatoire généré est négatif...
		aleat=aleat-2*aleat;} // ... le mettre en positif. ex: -99 -> 99
	else if(aleat==0){// si le nombre aléatoire généré est égal à 0...
		aleat=aleat+1;//... ajouter 1 au nombre
	}
}// fin de l'instruction

/*______________________________________________________________________________________*/

void niveaux()// définir le sous-programme niveaux
{ // début de l'instruction
	while (x==0){ // pour toujours
		displayBigTextLine(1, "Niveau1:1et50"); // afficher sur l'écran en petits caractères et à gauche à la ligne 1: Niveau1:1 et 50
		displayBigTextLine(3, "Niveau2:1et100");
		displayBigTextLine(5, "Niveau3:1et500");
		displayBigTextLine(7, "Niveau4:Perso");
		displayBigTextLine(10, "Choix du niveau:");
		displayCenteredBigTextLine(12, "-   %d  +", niveau); // afficher sur l'écran en gros caractères et centré à la ligne 6 - et + aux extrémités et la valeur de la variable niveau au milieu

		if(getButtonPress(buttonLeft)){ // si le bouton gauche du NXT est enfoncé
			playSoundFile("Click"); // jouer un clic
			niveau=niveau-1; // diminuer d'un niveau
			displayCenteredBigTextLine(12, "-   %d  +", niveau);
			sleep(500);}// attendre 500 millisecondes
		if(getButtonPress(buttonRight)){ //si le bouton gauche du NXT est enfoncé
			playSoundFile("Click");
			niveau=niveau+1;// augmenter d'un niveau
			displayCenteredBigTextLine(12, "-   %d  +", niveau);
			sleep(500);}
		if(getButtonPress(buttonEnter)){//si le bouton entrée du NXT est enfoncé
			playSoundFile("Click");
			displayClearTextLine(5);// effacer la ligne 5 de l'écran
			sleep(500);
			if(niveau==1){ // si l'utilisateur a choisi le niveau 1
				maxi=50; // la borne maximale de la recherche d'un nombre aléatoire est 50
				break;}
			if(niveau==2){// si l'utilisateur a choisi le niveau 2
				maxi=100;// la borne maximale de la recherche d'un nombre aléatoire est 100
				break;}
			if(niveau==3){// si l'utilisateur a choisi le niveau 3
				maxi=500;// la borne maximale de la recherche d'un nombre aléatoire est 500
				break;}
			if(niveau==4){// si l'utilisateur a choisi le niveau 4
				eraseDisplay(); // effacer tout l'écran
				displayCenteredBigTextLine(1, " Nombre maximum");// afficher en petits caractères et centré à la ligne 1 Nombre maximum
				displayCenteredBigTextLine(3, "%d", maxi);// afficher la valeur de la variable maxi
				sleep(1000);
				while(x==0)
				{ // tant que le bouton entrée du NXT n'est pas enfoncé...
					if(getButtonPress(buttonLeft)){
						playSoundFile("Click");
						maxi=maxi-1;
						displayCenteredBigTextLine(3, "%d", maxi);
						sleep(300);}

					if(SensorValue(touch1) == 1){//... si le capteur tactile pour diminuer est enfoncé
						while(SensorValue(touch1) == 1){// tant que le capteur tactile pour diminuer est enfoncé...
							maxi=maxi-1;//... diminuer la valeur de maxi de 1
							displayCenteredBigTextLine(3, "%d", maxi);
							sleep(2);}
						playSoundFile("Click");}

					if(getButtonPress(buttonRight)){//... si le capteur tactile pour augmenter est enfoncé
						playSoundFile("Click");
						maxi=maxi+1;
						displayCenteredBigTextLine(3, "%d", maxi);
						sleep(300);}

					if(SensorValue(touch4) == 1){//... si le capteur tactile pour augmenter est enfoncé
						while(SensorValue(touch4) == 1){// tant que le capteur tactile pour augmenter est enfoncé...

							maxi=maxi+1;//... augmenter la valeur de maxi de 1
							displayCenteredBigTextLine(3, "%d", maxi);
							sleep(2);}
						playSoundFile("Click");}// jouer le clic juste à la fin pour ne l'avoir qu'une fois qu'on relache

					if(getButtonPress(buttonEnter)){
						playSoundFile("Click");
						eraseDisplay();
						displayCenteredBigTextLine(3, "Ok");
						sleep(2000);
						x=1;
						break;
					}// sortir du sous-programme
				}
			}
		}
	}
}

/*______________________________________________________________________________________*/
task negatif()
{// tâche pour gérer tous les nombres à l'extérieur des bornes
	while(repete==0)
	{
		if (maxi<=0){
			user=1;
			displayCenteredBigTextLine(7, "%d",user );
		}
		if (niveau<1){
			niveau=4;
			displayCenteredBigTextLine(12, "-   %d  +", niveau);}
		if (niveau>4){
			niveau=1;
			displayCenteredBigTextLine(12, "-   %d  +", niveau);}
		if (user<=0){
			user=maxi;
			displayCenteredBigTextLine(7, "%d",user );
		}
		if (user>maxi){
			user=1;
			displayCenteredBigTextLine(7, "%d",user );
		}
		if (maxi<1){
			maxi=1;
			displayCenteredBigTextLine(7, "%d",maxi );
		}
	}
}


/*______________________________________________________________________________________*/




task main()
// programme principal
{
	//a=0;
	while(repete==0){// tant que l'utilisateur joue et rejoue
		nVolume=100; // mettre le son au maximum
		startTask(negatif);// démarrer la tache negatif
		niveaux(); // démarrer le sous-programme niveaux
		startTask (aleatoire);// démarrer la tache negatif
		playSoundFile("Start up"); // jouer le son NXT ! Startup
		eraseDisplay(); // effacer tout l'écran
		user=1;
		a=0;
		z=0;
		sleep(1000);
		displayCenteredBigTextLine(1, "Entre 1 et %d", maxi); // entre 1 et borne maxi définie avant
		displayCenteredBigTextLine(12, "-     +");
		displayCenteredBigTextLine(4, "Votre nombre :");
		displayCenteredBigTextLine(7, "%d", user);


		while(a==0) // pour toujours
		{


			if(getButtonPress(buttonLeft)){
				playSoundFile("Click");
				user=user-1;
				displayCenteredBigTextLine(7, "%d", user);
				sleep(300);}

			if(SensorValue(touch1) == 1){
				while(SensorValue(touch1) == 1){

					user=user-1;
					displayCenteredBigTextLine(7, "%d", user);
					sleep(2);} // attendre 2 millisecondes pour aller plus vite
				playSoundFile("Click");}

			if(getButtonPress(buttonRight)){
				playSoundFile("Click");
				user=user+1;
				displayCenteredBigTextLine(7, "%d", user);
				sleep(300);}

			if(SensorValue(touch4) == 1){
				while(SensorValue(touch4) == 1){

					user=user+1;
					displayCenteredBigTextLine(7, "%d", user);
					sleep(2);}
				playSoundFile("Click");}

			if(getButtonPress(buttonEnter))
			{ // si l'utilisateur valide
				while(getButtonPress(buttonEnter)){}// tant qu'il appuie ne rien faire
				coups=coups+1; // augmenter le nombre de coups
				playSoundFile("Click");
				displayClearTextLine(6);
				sleep(500);
				if(user<aleat){ // si le nombre de l'utilisateur est plus grand que le nombre généré...
					displayClearTextLine(10);
					displayCenteredBigTextLine(10, "C'est plus"); //... écrire c'est plus


					}else if(user>aleat){
					displayClearTextLine(10);
					displayCenteredBigTextLine(10, "C'est moins");

				}else if(user==aleat)// si le nombre de l'utilisateur est le nombre généré...
				{
					playSoundFile("Bravo"); // applaudissment
					displayClearTextLine(10);
					displayCenteredBigTextLine(10, "C'est bon"); /// écrire c'est bon
					sleep(2000);
					eraseDisplay(); // effacer l'écran
					displayCenteredBigTextLine(4,"Rejouer?");
					displayCenteredBigTextLine(1, "En %d coups", coups);
					displayCenteredBigTextLine(10, "Non  Oui");
					while(z==0){// tant que l'utilisateur n'appuie pas, ne rien faire
						if(getButtonPress(buttonLeft)){ // s'il ne veut pas rejouer
							playSoundFile("Click");
							z=1;
							y=1;// arreter while grâce à repete
							stopAllTasks();

							break;} // sortir de la boucle et donc grace à repetedu programme
						if(getButtonPress(buttonRight)){ // s'il veut rejouer
							playSoundFile("Click");
							stopTask(negatif);
							stopTask(aleatoire);
							coups=0; // réinitialiser le nombre de coups ...
							maxi=1; // ... et le nombre maximum
							x=0;
							a=1;
							z=1;
							break;

						} // sorir de la boucle et redémmarer le programme
					}
				}
			}
		}
	}
}
